version: '3.8'

services:
  microservicerestapi:
    build: ./MicroserviceRestApi
    container_name: microservicerestapi
    ports:
      - "5000:80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=GymIoDatabase;Username=postgres;Password=Your_password123;
    networks:
      app-network:
        aliases:
          - microservicerestapi
    restart: always

  microservicepdfgenerator:
    build: ./MicroservicePdfGenerator
    container_name: microservicepdfgenerator
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=GymIoDatabase;Username=postgres;Password=Your_password123;
      - REST_API_URL=http://microservicerestapi/
    volumes:
      - reports-data:/app/reports
    networks:
      app-network:
        aliases:
          - microservicepdfgenerator
    restart: always

  microserviceweb:
    build: ./MicroserviceWeb
    container_name: microserviceweb
    ports:
      - "8080:80"
    depends_on:
      - microservicepdfgenerator
    volumes:
      - reports-data:/app/reports
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REST_API_URL=http://microservicerestapi/
    networks:
      app-network:
        aliases:
          - microserviceweb
    restart: always

  database:
    image: postgres:15
    container_name: database
    environment:
      - POSTGRES_DB=GymIoDatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Your_password123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  db-data:
  reports-data:
